title: Jun He's Hand-Written Notes
description: >-
  Hand-written contents in the AI era in computer science and miscellaneous topics. The contents on this site does not represent the views of my employer.
baseurl: ""
url: "https://junhe.github.io"
github_username: junhe

theme: minima

plugins:
  - jekyll-feed
