title: Jun He's hand-written notes
description: >-
baseurl: ""
url: "https://junhe.github.io"
github_username: junhe

theme: minima

plugins:
  - jekyll-feed

sass:
  quiet_deps: true
  silence_deprecations:
    - import
